# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-crux" do
  # staged_path is a Homebrew template token, not the Ruby method the
  # postflight block used, and goreleaser renders this through Go's
  # templating first, so the braces are escaped to survive it.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/git-crux"], must_succeed: false
  end

  version "1.4.0"

  on_macos do
    on_arm do
      sha256 "959d0e124a9026ba8bce88f82ac11027bd6179e8459dbbba9ab9ea9147ae81e3"
      url "https://github.com/jonhadfield/git-crux/releases/download/v#{version}/git-crux_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dd6c073fdd2871284d0545fd98f1e75b368e17ef06e981dbc738f76900990543"
      url "https://github.com/jonhadfield/git-crux/releases/download/v#{version}/git-crux_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1078b62f42147c5482f97acd96fcb1a38fcccfff7449b09098869a6fa58df92c"
      url "https://github.com/jonhadfield/git-crux/releases/download/v#{version}/git-crux_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "954f8cb331173cbcc9e0602c4b4fe5d84e586b999c72d5bad859c34f6c4b9f82"
      url "https://github.com/jonhadfield/git-crux/releases/download/v#{version}/git-crux_linux_amd64.tar.gz"
    end
  end

  name "git-crux"
  desc "AI commit-message reviewer that checks your message against the staged diff"
  homepage "https://github.com/jonhadfield/git-crux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-crux"

  # No zap stanza required
end
