# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-crux" do
  # staged_path is a Homebrew template token, not the Ruby method the
  # postflight block used, and goreleaser renders this through Go's
  # templating first, so the braces are escaped to survive it.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/git-crux"], must_succeed: false
  end

  version "1.1.1"

  on_macos do
    on_arm do
      sha256 "65024a092017f5272f255023c67c8f9642191d62283979f6299457c28f0d0653"
      url "https://github.com/jonhadfield/git-crux/releases/download/v#{version}/git-crux_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "281dbc519bd8759659ae74dfa78af8ad8454181981a7694ded860e18ad406044"
      url "https://github.com/jonhadfield/git-crux/releases/download/v#{version}/git-crux_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ace157df65bb72f090fbedb8f934327d2f73c46356c2ac31cbfb6877bb5f1051"
      url "https://github.com/jonhadfield/git-crux/releases/download/v#{version}/git-crux_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e87da6a94c66dee8325ddefb9626a9ee75420e0a788910e78185685640200186"
      url "https://github.com/jonhadfield/git-crux/releases/download/v#{version}/git-crux_linux_amd64.tar.gz"
    end
  end

  name "git-crux"
  desc "AI commit-message reviewer that checks your message against the staged diff"
  homepage "https://github.com/jonhadfield/git-crux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-crux"

  # No zap stanza required
end
