# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-crux" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "18aad54a5aefab35aa0add41a31bb3fdb7a014cd83e352fe6bc95069ce72d1e9"
      url "https://github.com/jonhadfield/git-crux/releases/download/v#{version}/git-crux_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6d316b40eeb01152b9ec62322e1ec0a6290e66cc5f1590fc6363d175e6359de2"
      url "https://github.com/jonhadfield/git-crux/releases/download/v#{version}/git-crux_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "597ba438d1510e8c6fe978cf2e6422713e3e2c3007dbf9fb18d878d66ab1782d"
      url "https://github.com/jonhadfield/git-crux/releases/download/v#{version}/git-crux_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ee21e3b3e721a6293dfe4fee892677f77b4e45ec6a0c168f25577bdfac99166"
      url "https://github.com/jonhadfield/git-crux/releases/download/v#{version}/git-crux_linux_amd64.tar.gz"
    end
  end

  name "git-crux"
  desc "AI commit-message reviewer that checks your message against the staged diff"
  homepage "https://github.com/jonhadfield/git-crux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-crux"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-crux"]
    end
  end

  # No zap stanza required
end
