# This file was generated by GoReleaser. DO NOT EDIT.
cask "ip-fetcher" do
  version "0.0.29"

  on_macos do
    on_arm do
      sha256 "a290ce892c66ff97411fd929e443b6b50b961649da8df0bd02b1fe8757407395"
      url "https://github.com/jonhadfield/ip-fetcher/releases/download/v#{version}/ip-fetcher_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f3c9c44248ff918e2899e05110a9b6b53728d4f71d54a72d00db6258a18a763f"
      url "https://github.com/jonhadfield/ip-fetcher/releases/download/v#{version}/ip-fetcher_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dbe7b2bebef7f93cd3bb90fe4475953bfe6b939c88a644082b3df37684a8f537"
      url "https://github.com/jonhadfield/ip-fetcher/releases/download/v#{version}/ip-fetcher_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "16e0782df0b08596c3e250cb2c3fc6b3ee9da17b9a207a81fb3fd4c9e5fa2668"
      url "https://github.com/jonhadfield/ip-fetcher/releases/download/v#{version}/ip-fetcher_linux_amd64.tar.gz"
    end
  end

  name "ip-fetcher"
  desc "A go library and CLI to fetch IP ranges from popular online sources"
  homepage "https://github.com/jonhadfield/ip-fetcher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ip-fetcher"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ip-fetcher"]
    end
  end

  # No zap stanza required
end
