# This file was generated by GoReleaser. DO NOT EDIT.
cask "ip-fetcher" do
  version "0.0.30"

  on_macos do
    on_arm do
      sha256 "c207bd39a4cb234ce0af3898cf1896b42d8c5bf6a84fd5889b10fcd9fc77075b"
      url "https://github.com/jonhadfield/ip-fetcher/releases/download/v#{version}/ip-fetcher_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c1a80782146eb05e037786ce2d4862a24fe7403254e3c23db949ef9ab5e56a26"
      url "https://github.com/jonhadfield/ip-fetcher/releases/download/v#{version}/ip-fetcher_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b1bbaec4e3223e35772779baeb4be759f9e536a10984211232d09bdf818dc0a2"
      url "https://github.com/jonhadfield/ip-fetcher/releases/download/v#{version}/ip-fetcher_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b8226296b2e108050297c0993baddb6944cbc6a5fb2bc4dc1d5453d3d336b3fa"
      url "https://github.com/jonhadfield/ip-fetcher/releases/download/v#{version}/ip-fetcher_linux_amd64.tar.gz"
    end
  end

  name "ip-fetcher"
  desc "A go library and CLI to fetch IP ranges from popular online sources"
  homepage "https://github.com/jonhadfield/ip-fetcher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ip-fetcher"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ip-fetcher"]
    end
  end

  # No zap stanza required
end
