# This file was generated by GoReleaser. DO NOT EDIT.
cask "ip-fetcher" do
  version "0.0.37"

  on_macos do
    on_arm do
      sha256 "301ab002b89cc1827f8a5957272ad714d8211be569a56ec922686afc4cddc957"
      url "https://github.com/jonhadfield/ip-fetcher/releases/download/v#{version}/ip-fetcher_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "703ed380b4a7ff495af98e1eded33f7c1afeea18f68cf7350d6e8f3bb6794aad"
      url "https://github.com/jonhadfield/ip-fetcher/releases/download/v#{version}/ip-fetcher_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e4d84c49d53f8eb912f8b33f62b9e39d2cfed748139a7495457e640d333bda50"
      url "https://github.com/jonhadfield/ip-fetcher/releases/download/v#{version}/ip-fetcher_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7ee829c29534e1ddb566f4306e4880c4f5547e6515b792eea71c5fdb14d7b4cb"
      url "https://github.com/jonhadfield/ip-fetcher/releases/download/v#{version}/ip-fetcher_linux_amd64.tar.gz"
    end
  end

  name "ip-fetcher"
  desc "A go library and CLI to fetch IP ranges from popular online sources"
  homepage "https://github.com/jonhadfield/ip-fetcher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ip-fetcher"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ip-fetcher"]
    end
  end

  # No zap stanza required
end
