# This file was generated by GoReleaser. DO NOT EDIT.
cask "orange-cli" do
  # staged_path is a Homebrew template token, not the Ruby method the
  # postflight block used, and goreleaser renders this through Go's
  # templating first, so the braces are escaped to survive it.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/orange"], must_succeed: false
  end

  version "0.5.8"

  on_macos do
    on_arm do
      sha256 "cf60db25a4c4b51d84e4e0f183324aae4f18db2e00db31bcb53aaa746b63d3dc"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5129c1a7e1847e3ba76fc442eb08f921594ea55a51b30e0f8b4b27f5a2ecf83f"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e20e50c797f9d15be693b12f3e63d6a2b91417b94af4c00e80f0e2a1c63b9398"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7fab7b2304699d9e6ba942f174b610a6eefe1ce1b2d64a223ce4cee1393c0dbd"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_linux_amd64.tar.gz"
    end
  end

  name "orange-cli"
  desc "Terminal reader for Hacker News"
  homepage "https://github.com/jonhadfield/orange"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orange"

  # No zap stanza required
end
