# This file was generated by GoReleaser. DO NOT EDIT.
cask "orange-cli" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "75481928612f6d8207f403fe26e7d91c7009d990f342abc208b6ca365bae65ee"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0189ecb71a83fbfac5e241e130992c4cda4103b488ab9a9cc4a89604cc5dec4d"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c7ac7b95869a9e2692bfaa034d0bb23f9ed85d33862920d1e35d1e525f777693"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "20ef2ff0ed40aed6d34aaf35f4210ae15aca6bbfbd63e25b5b05d2afaec842a6"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_linux_amd64.tar.gz"
    end
  end

  name "orange-cli"
  desc "Terminal reader for Hacker News"
  homepage "https://github.com/jonhadfield/orange"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orange"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orange"]
    end
  end

  # No zap stanza required
end
