# This file was generated by GoReleaser. DO NOT EDIT.
cask "orange" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "f36e081bbe07a2072d0a4a2c6d6aa8d20359bbd98b1fd841bc48603660438592"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa0f8c9303dd1f7f657beef64ed6d359508906751dec8123d1acde6868bdd715"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f8966f6219a4846cf7635406223ffe3726f5969d783e0484d3d500486990679"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fbef9ba2c55559c81c46cd400098c86de630b4d4e90f8817dffd3fb9ba857003"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_linux_arm64.tar.gz"
    end
  end

  name "orange"
  desc "Terminal reader for Hacker News"
  homepage "https://github.com/jonhadfield/orange"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orange"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orange"]
    end
  end

  # No zap stanza required

end
