# This file was generated by GoReleaser. DO NOT EDIT.
cask "orange" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "31973333ce98d104e3d40ab2d0f549378040de956c3cd62dabb0362ad3dac0af"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a13d13ab1b7fecc882f4ee55ea162e9e22714464dad3a7010c177dbc40f94ede"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "530d7b32e362f2850a35838248d9e642f1480bd65d139acc00db1f1a1418b4d4"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "304d223ecd90d4d41d85552fed357699df96f7b5e836bb4d6d01bcf07a62d0f6"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_linux_arm64.tar.gz"
    end
  end

  name "orange"
  desc "Terminal reader for Hacker News"
  homepage "https://github.com/jonhadfield/orange"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orange"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orange"]
    end
  end

  # No zap stanza required

end
