# This file was generated by GoReleaser. DO NOT EDIT.
cask "orange" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "2aef8c5ae971302117e036b4006ddb949ef8801376342d5d19359e045c66115e"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d07f31dddeb2b2e92718f4b789f2de9accff87a982737cafe4d494dc155da64"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6016b4b8c0a7f1d17b709a3f7cd3139c6bde0d0101b3bcd93aac9b674423b9ce"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0dd72d112d9078ff2d31b8eeb9ef0441cb9eba9c172d638b501a6fc99d86004"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_linux_arm64.tar.gz"
    end
  end

  name "orange"
  desc "Terminal reader for Hacker News"
  homepage "https://github.com/jonhadfield/orange"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orange"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orange"]
    end
  end

  # No zap stanza required

end
