# This file was generated by GoReleaser. DO NOT EDIT.
cask "orange-cli" do
  version "0.5.3"

  on_macos do
    on_arm do
      sha256 "9ea5730d62106ca43f4dbb6551238b036ffd80235a241d0f35aaf416ef34a17c"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d6caf23ffdbedb14ffe8c353d2d55f60f19000d7072742ce0c3e87ffa0c0e8e4"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c5c15bc8805f82d816aa16c2623e80d042649cd32dd3daff7b60c3a7184a3ba6"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "98d128cc5da782e3123d3eb6cab05b533701bd88c161281eddfbb630f049a013"
      url "https://github.com/jonhadfield/orange/releases/download/v#{version}/orange_linux_amd64.tar.gz"
    end
  end

  name "orange-cli"
  desc "Terminal reader for Hacker News"
  homepage "https://github.com/jonhadfield/orange"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orange"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orange"]
    end
  end

  # No zap stanza required
end
