# This file was generated by GoReleaser. DO NOT EDIT.
cask "sn-cli" do
  version "0.5.2"

  on_macos do
    sha256 "5e59213e48aaf29e002cb89ae13f0c6dc5c2b9cf48ec7b1e2a59e0093c14884d"
    url "https://github.com/jonhadfield/sn-cli/releases/download/#{version}/sn-cli_Darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "bb7a6fd4071d3988b99d81d905545e80e46ff3844e6c9a0ff2691b3d78e12c18"
      url "https://github.com/jonhadfield/sn-cli/releases/download/#{version}/sn-cli_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3926a08a003a2b1591d5c0eaca11e808df62072d3151f1cfd0f3d62218bca88f"
      url "https://github.com/jonhadfield/sn-cli/releases/download/#{version}/sn-cli_Linux_x86_64.tar.gz"
    end
  end

  name "sn-cli"
  desc "A command-line interface for Standard Notes"
  homepage "https://github.com/jonhadfield/sn-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sn"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sn"]
    end
  end

  # No zap stanza required
end
