# This file was generated by GoReleaser. DO NOT EDIT.
cask "sn-cli" do
  # staged_path is a Homebrew template token, not the Ruby method the
  # postflight block used, and goreleaser renders this through Go's
  # templating first, so the braces are escaped to survive it.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/sn"], must_succeed: false
  end

  version "0.6.0"

  on_macos do
    sha256 "a75558f679dca7a5b7c48b3f928719f85e643577f6ae9a9574aa5822d659ee74"
    url "https://github.com/jonhadfield/sn-cli/releases/download/#{version}/sn-cli_Darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "4a8b55a2ea908b298a8109a185f9812f55a505a423016f5fba763900111d9028"
      url "https://github.com/jonhadfield/sn-cli/releases/download/#{version}/sn-cli_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "effe3d9900b3e4785137e687d35aec792dc50999cac86b769c9cd35685b8bd41"
      url "https://github.com/jonhadfield/sn-cli/releases/download/#{version}/sn-cli_Linux_x86_64.tar.gz"
    end
  end

  name "sn-cli"
  desc "A command-line interface for Standard Notes"
  homepage "https://github.com/jonhadfield/sn-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sn"

  # No zap stanza required
end
