# This file was generated by GoReleaser. DO NOT EDIT.
cask "sn-cli" do
  # staged_path is a Homebrew template token, not the Ruby method the
  # postflight block used, and goreleaser renders this through Go's
  # templating first, so the braces are escaped to survive it.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/sn"], must_succeed: false
  end

  version "0.5.3"

  on_macos do
    sha256 "c5b778ecd9d8f2ab25fcd16c6ff4f2d42ddcde3fc2596cd7b0cf3f33e37455a4"
    url "https://github.com/jonhadfield/sn-cli/releases/download/#{version}/sn-cli_Darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "a4332a5523a2e40b2ab42fcd10b822e7b4d153d70d27c4ad859d70af76ee1b0f"
      url "https://github.com/jonhadfield/sn-cli/releases/download/#{version}/sn-cli_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b821ef633584f7dd7cce23b450e7f6597c10aed8356acc8bc2847fce92418ac0"
      url "https://github.com/jonhadfield/sn-cli/releases/download/#{version}/sn-cli_Linux_x86_64.tar.gz"
    end
  end

  name "sn-cli"
  desc "A command-line interface for Standard Notes"
  homepage "https://github.com/jonhadfield/sn-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sn"

  # No zap stanza required
end
