# This file was generated by GoReleaser. DO NOT EDIT.
cask "sn-dotfiles" do
  # staged_path is a Homebrew template token, not the Ruby method the
  # postflight block used, and goreleaser renders this through Go's
  # templating first, so the braces are escaped to survive it.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/sn-dotfiles"], must_succeed: false
  end

  version "0.5.0"

  on_macos do
    sha256 "ec92fcc30905f40cd3ac6098c4886717555e7620401f7ebb114b6f582326cbd1"
    url "https://github.com/jonhadfield/sn-dotfiles/releases/download/#{version}/sn-dotfiles_Darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "6f9b4713b1fe7ec7c66ffac7143ac79fbb5a2f54a6a5f9795ad95454a79c3df6"
      url "https://github.com/jonhadfield/sn-dotfiles/releases/download/#{version}/sn-dotfiles_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3a2b6a796971ed07d47615bbb41a0b0ea13fffd0185f5449c55d4ccb00f38773"
      url "https://github.com/jonhadfield/sn-dotfiles/releases/download/#{version}/sn-dotfiles_Linux_x86_64.tar.gz"
    end
  end

  name "sn-dotfiles"
  desc "Manage your dotfiles with Standard Notes"
  homepage "https://github.com/jonhadfield/sn-dotfiles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sn-dotfiles"

  # No zap stanza required
end
