# This file was generated by GoReleaser. DO NOT EDIT.
cask "sn-dotfiles" do
  # staged_path is a Homebrew template token, not the Ruby method the
  # postflight block used, and goreleaser renders this through Go's
  # templating first, so the braces are escaped to survive it.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/sn-dotfiles"], must_succeed: false
  end

  version "0.2.0"

  on_macos do
    sha256 "48e54b079733273900ff265e5110a898fd2ea0a7c1d3f9e0e7416a271c94a3cb"
    url "https://github.com/jonhadfield/sn-dotfiles/releases/download/#{version}/sn-dotfiles_Darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "ea6cb3a28f90c05882bfacfc4297d1a0ed2cd7033d35da1c50d451d3b9e78012"
      url "https://github.com/jonhadfield/sn-dotfiles/releases/download/#{version}/sn-dotfiles_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "07733156c13ff373e1d96dc44a94d028c3213af0a8472a9a6509ca99d531a392"
      url "https://github.com/jonhadfield/sn-dotfiles/releases/download/#{version}/sn-dotfiles_Linux_x86_64.tar.gz"
    end
  end

  name "sn-dotfiles"
  desc "Manage your dotfiles with Standard Notes"
  homepage "https://github.com/jonhadfield/sn-dotfiles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sn-dotfiles"

  # No zap stanza required
end
