# This file was generated by GoReleaser. DO NOT EDIT.
cask "sn-dotfiles" do
  # staged_path is a Homebrew template token, not the Ruby method the
  # postflight block used, and goreleaser renders this through Go's
  # templating first, so the braces are escaped to survive it.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/sn-dotfiles"], must_succeed: false
  end

  version "0.3.0"

  on_macos do
    sha256 "1e47765575adb9d72a5b40a0375f27bb0ddad127b1029a20c194b74d3ae19e38"
    url "https://github.com/jonhadfield/sn-dotfiles/releases/download/#{version}/sn-dotfiles_Darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "ee357315ac445c421b32f0d39289a258619cacb5e919ddd39630447bcc91c8ae"
      url "https://github.com/jonhadfield/sn-dotfiles/releases/download/#{version}/sn-dotfiles_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "89270760922b96f3a6ab55f89b02c4b47840bfb70006795f6a18a2a86cdff7ac"
      url "https://github.com/jonhadfield/sn-dotfiles/releases/download/#{version}/sn-dotfiles_Linux_x86_64.tar.gz"
    end
  end

  name "sn-dotfiles"
  desc "Manage your dotfiles with Standard Notes"
  homepage "https://github.com/jonhadfield/sn-dotfiles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sn-dotfiles"

  # No zap stanza required
end
