# This file was generated by GoReleaser. DO NOT EDIT.
cask "subtocheck" do
  # staged_path is a Homebrew template token, escaped to survive
  # goreleaser's own templating.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/subtocheck"], must_succeed: false
  end

  version "0.0.8"

  on_macos do
    on_arm do
      sha256 "4c8da06735cd8d79963940cd4e7d41ac98594bd5eb183ab6216ff64ada21650a"
      url "https://github.com/jonhadfield/subtocheck/releases/download/v#{version}/subtocheck_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "829970b254939571cd0574d18f78f49eb4e47e46dad02ea7ed7afb203f919946"
      url "https://github.com/jonhadfield/subtocheck/releases/download/v#{version}/subtocheck_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "37682e610b76783798d075779b81980e9cca89eb815b8da9ed7268c0fbed21d0"
      url "https://github.com/jonhadfield/subtocheck/releases/download/v#{version}/subtocheck_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d90b0d09bdc1c7dc95eaeb11913ee0aa8bf297dfbb6670a44515369c4e6eb52c"
      url "https://github.com/jonhadfield/subtocheck/releases/download/v#{version}/subtocheck_linux_amd64.tar.gz"
    end
  end

  name "subtocheck"
  desc "Check FQDNs for subdomain takeover vulnerabilities"
  homepage "https://github.com/jonhadfield/subtocheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "subtocheck"

  # No zap stanza required
end
