# This file was generated by GoReleaser. DO NOT EDIT.
cask "subtocheck" do
  # staged_path is a Homebrew template token, escaped to survive
  # goreleaser's own templating.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/subtocheck"], must_succeed: false
  end

  version "0.0.10"

  on_macos do
    on_arm do
      sha256 "690f6ea215df1d5f7085456324dc367aaae144b5a1049b692e13256beee11d78"
      url "https://github.com/jonhadfield/subtocheck/releases/download/v#{version}/subtocheck_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "799e7e5156818b3a1a4050dcf3ee835675680a2b5488cd0191eb343e92eccd46"
      url "https://github.com/jonhadfield/subtocheck/releases/download/v#{version}/subtocheck_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c058e568c9ff176ccfd340272e3572182ff3cae030a56c3e7d16aa7345deb8ad"
      url "https://github.com/jonhadfield/subtocheck/releases/download/v#{version}/subtocheck_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b79514d710a56be05150128f7e08eae58ab291fa527bd1bfc8d3f25e2fb179b"
      url "https://github.com/jonhadfield/subtocheck/releases/download/v#{version}/subtocheck_linux_amd64.tar.gz"
    end
  end

  name "subtocheck"
  desc "Check FQDNs for subdomain takeover vulnerabilities"
  homepage "https://github.com/jonhadfield/subtocheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "subtocheck"

  # No zap stanza required
end
