# This file was generated by GoReleaser. DO NOT EDIT.
cask "subtocheck" do
  # staged_path is a Homebrew template token, escaped to survive
  # goreleaser's own templating.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/subtocheck"], must_succeed: false
  end

  version "0.0.7"

  on_macos do
    on_arm do
      sha256 "1d14db316ca0381324b41ad9e20f7cc0666366731e3cd25f05bafa4fd1097a6a"
      url "https://github.com/jonhadfield/subtocheck/releases/download/v#{version}/subtocheck_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6f556a4803f568cfe9e4557e260f811518594cc91e24b7960c1762649bca0a0f"
      url "https://github.com/jonhadfield/subtocheck/releases/download/v#{version}/subtocheck_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7cb9a1ea17fa22d8d8d58b6475ff0266303a76754bfa84686ee653d27aa05d4c"
      url "https://github.com/jonhadfield/subtocheck/releases/download/v#{version}/subtocheck_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6fe395f7b44f971d4a85124501daa6fef8383be79ab8e21acaae65875f85d2dc"
      url "https://github.com/jonhadfield/subtocheck/releases/download/v#{version}/subtocheck_linux_amd64.tar.gz"
    end
  end

  name "subtocheck"
  desc "Check FQDNs for subdomain takeover vulnerabilities"
  homepage "https://github.com/jonhadfield/subtocheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "subtocheck"

  # No zap stanza required
end
